name: keras2c_test
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - libexpat=2.6.2
  - libffi=3.4.2
  - libsqlite=3.46.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.3.1
  - pip=24.0
  - python=3.11.5
  - readline=8.2
  - setuptools=70.1.1
  - tk=8.6.13
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.2.6
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.3.3
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - coverage==7.6.1
      - flatbuffers==24.3.25
      - gast==0.6.0
      - google-auth==2.31.0
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - grpcio==1.64.1
      - h5py==3.11.0
      - idna==3.7
      - iniconfig==2.0.0
      - keras==2.15.0
      - libclang==18.1.1
      - markdown==3.6
      - markupsafe==2.1.5
      - ml-dtypes==0.2.0
      - numpy==1.26.4
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==24.1
      - pluggy==1.5.0
      - protobuf==4.25.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pytest==8.3.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - six==1.16.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-macos==2.15.0
      - termcolor==2.4.0
      - typing-extensions==4.12.2
      - urllib3==2.2.2
      - werkzeug==3.0.3
      - wrapt==1.14.1
