name: Test

on:
  push:
    branches: master
    # paths:
    #   - '.github/workflows/test.yml'
    #   - 'keras2c/**'
    #   - 'tests/**'
    #   - 'include/**'
  pull_request:
    branches: master
    paths:
      - '.github/workflows/test.yml'
      - 'keras2c/**'
      - 'tests/**'
      - 'include/**'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Setup GCC
          uses: Dup4/actions-setup-gcc@v1
          with:
            version: latest
        # - uses: conda-incubator/setup-miniconda@v3
        #   with:
        #     activate-environment: keras2c_test
        #     environment-file: conda_keras2c_test.yml
        - name: Setup Python
          uses: actions/setup-python@master
          with:
            python-version: 3.11.5
        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v4.0.1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
        - run:
            pip install -r requirements.txt
            pip install -r tests/requirements.txt
            coverage run -m pytest
            coverage json
        - name: Update Coverage Badge
          # GitHub actions: default branch variable
          # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
          if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
          uses: we-cli/coverage-badge-action@main